"""autogenerated by genpy from humanMonitor/niut_SKELETON_STR.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import humanMonitor.msg

class niut_SKELETON_STR(genpy.Message):
  _md5sum = "d429f56f311dd3d55d503fb55fdca0ed"
  _type = "humanMonitor/niut_SKELETON_STR"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# IDL struct ::niut::SKELETON_STR
niut_JOINT_STR[25] joint
niut_JOINT unused

================================================================================
MSG: humanMonitor/niut_JOINT_STR
# IDL struct ::niut::JOINT_STR
float64 confidence
niut_GEN_POINT_3D position

================================================================================
MSG: humanMonitor/niut_GEN_POINT_3D
# IDL struct ::niut::GEN_POINT_3D
float64 x
float64 y
float64 z

================================================================================
MSG: humanMonitor/niut_JOINT
# IDL enum ::niut::JOINT
uint32 niut_ZERO = 0
uint32 niut_HEAD = 1
uint32 niut_NECK = 2
uint32 niut_TORSO = 3
uint32 niut_WAIST = 4
uint32 niut_LEFT_COLLAR = 5
uint32 niut_LEFT_SHOULDER = 6
uint32 niut_LEFT_ELBOW = 7
uint32 niut_LEFT_WRIST = 8
uint32 niut_LEFT_HAND = 9
uint32 niut_LEFT_FINGERTIP = 10
uint32 niut_RIGHT_COLLAR = 11
uint32 niut_RIGHT_SHOULDER = 12
uint32 niut_RIGHT_ELBOW = 13
uint32 niut_RIGHT_WRIST = 14
uint32 niut_RIGHT_HAND = 15
uint32 niut_RIGHT_FINGERTIP = 16
uint32 niut_LEFT_HIP = 17
uint32 niut_LEFT_KNEE = 18
uint32 niut_LEFT_ANKLE = 19
uint32 niut_LEFT_FOOT = 20
uint32 niut_RIGHT_HIP = 21
uint32 niut_RIGHT_KNEE = 22
uint32 niut_RIGHT_ANKLE = 23
uint32 niut_RIGHT_FOOT = 24

uint32 value

"""
  __slots__ = ['joint','unused']
  _slot_types = ['humanMonitor/niut_JOINT_STR[25]','humanMonitor/niut_JOINT']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint,unused

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(niut_SKELETON_STR, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.joint is None:
        self.joint = [humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR()]
      if self.unused is None:
        self.unused = humanMonitor.msg.niut_JOINT()
    else:
      self.joint = [humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR(),humanMonitor.msg.niut_JOINT_STR()]
      self.unused = humanMonitor.msg.niut_JOINT()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      for val1 in self.joint:
        buff.write(_struct_d.pack(val1.confidence))
        _v1 = val1.position
        _x = _v1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
      buff.write(_struct_I.pack(self.unused.value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.joint is None:
        self.joint = None
      if self.unused is None:
        self.unused = humanMonitor.msg.niut_JOINT()
      end = 0
      self.joint = []
      for i in range(0, 25):
        val1 = humanMonitor.msg.niut_JOINT_STR()
        start = end
        end += 8
        (val1.confidence,) = _struct_d.unpack(str[start:end])
        _v2 = val1.position
        _x = _v2
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        self.joint.append(val1)
      start = end
      end += 4
      (self.unused.value,) = _struct_I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      for val1 in self.joint:
        buff.write(_struct_d.pack(val1.confidence))
        _v3 = val1.position
        _x = _v3
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
      buff.write(_struct_I.pack(self.unused.value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.joint is None:
        self.joint = None
      if self.unused is None:
        self.unused = humanMonitor.msg.niut_JOINT()
      end = 0
      self.joint = []
      for i in range(0, 25):
        val1 = humanMonitor.msg.niut_JOINT_STR()
        start = end
        end += 8
        (val1.confidence,) = _struct_d.unpack(str[start:end])
        _v4 = val1.position
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        self.joint.append(val1)
      start = end
      end += 4
      (self.unused.value,) = _struct_I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d = struct.Struct("<d")
_struct_3d = struct.Struct("<3d")
