"""autogenerated by genpy from humanMonitor/niut_JOINT_STR.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import humanMonitor.msg

class niut_JOINT_STR(genpy.Message):
  _md5sum = "9c2906bba163fd7b5eea616563d91fcd"
  _type = "humanMonitor/niut_JOINT_STR"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# IDL struct ::niut::JOINT_STR
float64 confidence
niut_GEN_POINT_3D position

================================================================================
MSG: humanMonitor/niut_GEN_POINT_3D
# IDL struct ::niut::GEN_POINT_3D
float64 x
float64 y
float64 z

"""
  __slots__ = ['confidence','position']
  _slot_types = ['float64','humanMonitor/niut_GEN_POINT_3D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       confidence,position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(niut_JOINT_STR, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.confidence is None:
        self.confidence = 0.
      if self.position is None:
        self.position = humanMonitor.msg.niut_GEN_POINT_3D()
    else:
      self.confidence = 0.
      self.position = humanMonitor.msg.niut_GEN_POINT_3D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.confidence, _x.position.x, _x.position.y, _x.position.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = humanMonitor.msg.niut_GEN_POINT_3D()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.confidence, _x.position.x, _x.position.y, _x.position.z,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.confidence, _x.position.x, _x.position.y, _x.position.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = humanMonitor.msg.niut_GEN_POINT_3D()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.confidence, _x.position.x, _x.position.y, _x.position.z,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
