/* Auto-generated by genmsg_cpp for file /home/mfiore/catkin_ws/src/humanMonitor/msg/niut_SKELETON_STR.msg */
#ifndef HUMANMONITOR_MESSAGE_NIUT_SKELETON_STR_H
#define HUMANMONITOR_MESSAGE_NIUT_SKELETON_STR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "humanMonitor/niut_JOINT_STR.h"
#include "humanMonitor/niut_JOINT.h"

namespace humanMonitor
{
template <class ContainerAllocator>
struct niut_SKELETON_STR_ {
  typedef niut_SKELETON_STR_<ContainerAllocator> Type;

  niut_SKELETON_STR_()
  : joint()
  , unused()
  {
  }

  niut_SKELETON_STR_(const ContainerAllocator& _alloc)
  : joint()
  , unused(_alloc)
  {
    joint.assign( ::humanMonitor::niut_JOINT_STR_<ContainerAllocator> (_alloc));
  }

  typedef boost::array< ::humanMonitor::niut_JOINT_STR_<ContainerAllocator> , 25>  _joint_type;
  boost::array< ::humanMonitor::niut_JOINT_STR_<ContainerAllocator> , 25>  joint;

  typedef  ::humanMonitor::niut_JOINT_<ContainerAllocator>  _unused_type;
   ::humanMonitor::niut_JOINT_<ContainerAllocator>  unused;


  typedef boost::shared_ptr< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct niut_SKELETON_STR
typedef  ::humanMonitor::niut_SKELETON_STR_<std::allocator<void> > niut_SKELETON_STR;

typedef boost::shared_ptr< ::humanMonitor::niut_SKELETON_STR> niut_SKELETON_STRPtr;
typedef boost::shared_ptr< ::humanMonitor::niut_SKELETON_STR const> niut_SKELETON_STRConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace humanMonitor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d429f56f311dd3d55d503fb55fdca0ed";
  }

  static const char* value(const  ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd429f56f311dd3d5ULL;
  static const uint64_t static_value2 = 0x5d503fb55fdca0edULL;
};

template<class ContainerAllocator>
struct DataType< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "humanMonitor/niut_SKELETON_STR";
  }

  static const char* value(const  ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# IDL struct ::niut::SKELETON_STR\n\
niut_JOINT_STR[25] joint\n\
niut_JOINT unused\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_JOINT_STR\n\
# IDL struct ::niut::JOINT_STR\n\
float64 confidence\n\
niut_GEN_POINT_3D position\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_GEN_POINT_3D\n\
# IDL struct ::niut::GEN_POINT_3D\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_JOINT\n\
# IDL enum ::niut::JOINT\n\
uint32 niut_ZERO = 0\n\
uint32 niut_HEAD = 1\n\
uint32 niut_NECK = 2\n\
uint32 niut_TORSO = 3\n\
uint32 niut_WAIST = 4\n\
uint32 niut_LEFT_COLLAR = 5\n\
uint32 niut_LEFT_SHOULDER = 6\n\
uint32 niut_LEFT_ELBOW = 7\n\
uint32 niut_LEFT_WRIST = 8\n\
uint32 niut_LEFT_HAND = 9\n\
uint32 niut_LEFT_FINGERTIP = 10\n\
uint32 niut_RIGHT_COLLAR = 11\n\
uint32 niut_RIGHT_SHOULDER = 12\n\
uint32 niut_RIGHT_ELBOW = 13\n\
uint32 niut_RIGHT_WRIST = 14\n\
uint32 niut_RIGHT_HAND = 15\n\
uint32 niut_RIGHT_FINGERTIP = 16\n\
uint32 niut_LEFT_HIP = 17\n\
uint32 niut_LEFT_KNEE = 18\n\
uint32 niut_LEFT_ANKLE = 19\n\
uint32 niut_LEFT_FOOT = 20\n\
uint32 niut_RIGHT_HIP = 21\n\
uint32 niut_RIGHT_KNEE = 22\n\
uint32 niut_RIGHT_ANKLE = 23\n\
uint32 niut_RIGHT_FOOT = 24\n\
\n\
uint32 value\n\
\n\
";
  }

  static const char* value(const  ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint);
    stream.next(m.unused);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct niut_SKELETON_STR_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> & v) 
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::humanMonitor::niut_JOINT_STR_<ContainerAllocator> >::stream(s, indent + "    ", v.joint[i]);
    }
    s << indent << "unused: ";
s << std::endl;
    Printer< ::humanMonitor::niut_JOINT_<ContainerAllocator> >::stream(s, indent + "  ", v.unused);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUMANMONITOR_MESSAGE_NIUT_SKELETON_STR_H

