/* Auto-generated by genmsg_cpp for file /home/mfiore/catkin_ws/src/humanMonitor/msg/niut_USER_STR.msg */
#ifndef HUMANMONITOR_MESSAGE_NIUT_USER_STR_H
#define HUMANMONITOR_MESSAGE_NIUT_USER_STR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "humanMonitor/niut_TIME_STR.h"
#include "humanMonitor/niut_TIME_STR.h"
#include "humanMonitor/niut_TRACK_STATE.h"
#include "humanMonitor/niut_SKELETON_STR.h"

namespace humanMonitor
{
template <class ContainerAllocator>
struct niut_USER_STR_ {
  typedef niut_USER_STR_<ContainerAllocator> Type;

  niut_USER_STR_()
  : id(0)
  , trackedId(0)
  , date_discovered()
  , date()
  , state()
  , skeleton()
  {
  }

  niut_USER_STR_(const ContainerAllocator& _alloc)
  : id(0)
  , trackedId(0)
  , date_discovered(_alloc)
  , date(_alloc)
  , state(_alloc)
  , skeleton(_alloc)
  {
  }

  typedef int32_t _id_type;
  int32_t id;

  typedef int32_t _trackedId_type;
  int32_t trackedId;

  typedef  ::humanMonitor::niut_TIME_STR_<ContainerAllocator>  _date_discovered_type;
   ::humanMonitor::niut_TIME_STR_<ContainerAllocator>  date_discovered;

  typedef  ::humanMonitor::niut_TIME_STR_<ContainerAllocator>  _date_type;
   ::humanMonitor::niut_TIME_STR_<ContainerAllocator>  date;

  typedef  ::humanMonitor::niut_TRACK_STATE_<ContainerAllocator>  _state_type;
   ::humanMonitor::niut_TRACK_STATE_<ContainerAllocator>  state;

  typedef  ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator>  _skeleton_type;
   ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator>  skeleton;


  typedef boost::shared_ptr< ::humanMonitor::niut_USER_STR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanMonitor::niut_USER_STR_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct niut_USER_STR
typedef  ::humanMonitor::niut_USER_STR_<std::allocator<void> > niut_USER_STR;

typedef boost::shared_ptr< ::humanMonitor::niut_USER_STR> niut_USER_STRPtr;
typedef boost::shared_ptr< ::humanMonitor::niut_USER_STR const> niut_USER_STRConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::humanMonitor::niut_USER_STR_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::humanMonitor::niut_USER_STR_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace humanMonitor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::humanMonitor::niut_USER_STR_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::humanMonitor::niut_USER_STR_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::humanMonitor::niut_USER_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c73ff86e7f31e732cc4478587d7e6354";
  }

  static const char* value(const  ::humanMonitor::niut_USER_STR_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc73ff86e7f31e732ULL;
  static const uint64_t static_value2 = 0xcc4478587d7e6354ULL;
};

template<class ContainerAllocator>
struct DataType< ::humanMonitor::niut_USER_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "humanMonitor/niut_USER_STR";
  }

  static const char* value(const  ::humanMonitor::niut_USER_STR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::humanMonitor::niut_USER_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# IDL struct ::niut::USER_STR\n\
int32 id\n\
int32 trackedId\n\
niut_TIME_STR date_discovered\n\
niut_TIME_STR date\n\
niut_TRACK_STATE state\n\
niut_SKELETON_STR skeleton\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_TIME_STR\n\
# IDL struct ::niut::TIME_STR\n\
uint32 t_sec\n\
uint32 t_usec\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_TRACK_STATE\n\
# IDL enum ::niut::TRACK_STATE\n\
uint32 niut_NO_TRACKING = 0\n\
uint32 niut_POSE_SEARCH = 1\n\
uint32 niut_CALIBRATE = 2\n\
uint32 niut_TRACKING = 3\n\
\n\
uint32 value\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_SKELETON_STR\n\
# IDL struct ::niut::SKELETON_STR\n\
niut_JOINT_STR[25] joint\n\
niut_JOINT unused\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_JOINT_STR\n\
# IDL struct ::niut::JOINT_STR\n\
float64 confidence\n\
niut_GEN_POINT_3D position\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_GEN_POINT_3D\n\
# IDL struct ::niut::GEN_POINT_3D\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: humanMonitor/niut_JOINT\n\
# IDL enum ::niut::JOINT\n\
uint32 niut_ZERO = 0\n\
uint32 niut_HEAD = 1\n\
uint32 niut_NECK = 2\n\
uint32 niut_TORSO = 3\n\
uint32 niut_WAIST = 4\n\
uint32 niut_LEFT_COLLAR = 5\n\
uint32 niut_LEFT_SHOULDER = 6\n\
uint32 niut_LEFT_ELBOW = 7\n\
uint32 niut_LEFT_WRIST = 8\n\
uint32 niut_LEFT_HAND = 9\n\
uint32 niut_LEFT_FINGERTIP = 10\n\
uint32 niut_RIGHT_COLLAR = 11\n\
uint32 niut_RIGHT_SHOULDER = 12\n\
uint32 niut_RIGHT_ELBOW = 13\n\
uint32 niut_RIGHT_WRIST = 14\n\
uint32 niut_RIGHT_HAND = 15\n\
uint32 niut_RIGHT_FINGERTIP = 16\n\
uint32 niut_LEFT_HIP = 17\n\
uint32 niut_LEFT_KNEE = 18\n\
uint32 niut_LEFT_ANKLE = 19\n\
uint32 niut_LEFT_FOOT = 20\n\
uint32 niut_RIGHT_HIP = 21\n\
uint32 niut_RIGHT_KNEE = 22\n\
uint32 niut_RIGHT_ANKLE = 23\n\
uint32 niut_RIGHT_FOOT = 24\n\
\n\
uint32 value\n\
\n\
";
  }

  static const char* value(const  ::humanMonitor::niut_USER_STR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::humanMonitor::niut_USER_STR_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::humanMonitor::niut_USER_STR_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.trackedId);
    stream.next(m.date_discovered);
    stream.next(m.date);
    stream.next(m.state);
    stream.next(m.skeleton);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct niut_USER_STR_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanMonitor::niut_USER_STR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::humanMonitor::niut_USER_STR_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "trackedId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.trackedId);
    s << indent << "date_discovered: ";
s << std::endl;
    Printer< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> >::stream(s, indent + "  ", v.date_discovered);
    s << indent << "date: ";
s << std::endl;
    Printer< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> >::stream(s, indent + "  ", v.date);
    s << indent << "state: ";
s << std::endl;
    Printer< ::humanMonitor::niut_TRACK_STATE_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "skeleton: ";
s << std::endl;
    Printer< ::humanMonitor::niut_SKELETON_STR_<ContainerAllocator> >::stream(s, indent + "  ", v.skeleton);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUMANMONITOR_MESSAGE_NIUT_USER_STR_H

