/* Auto-generated by genmsg_cpp for file /home/mfiore/catkin_ws/src/humanMonitor/msg/niut_TIME_STR.msg */
#ifndef HUMANMONITOR_MESSAGE_NIUT_TIME_STR_H
#define HUMANMONITOR_MESSAGE_NIUT_TIME_STR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace humanMonitor
{
template <class ContainerAllocator>
struct niut_TIME_STR_ {
  typedef niut_TIME_STR_<ContainerAllocator> Type;

  niut_TIME_STR_()
  : t_sec(0)
  , t_usec(0)
  {
  }

  niut_TIME_STR_(const ContainerAllocator& _alloc)
  : t_sec(0)
  , t_usec(0)
  {
  }

  typedef uint32_t _t_sec_type;
  uint32_t t_sec;

  typedef uint32_t _t_usec_type;
  uint32_t t_usec;


  typedef boost::shared_ptr< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanMonitor::niut_TIME_STR_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct niut_TIME_STR
typedef  ::humanMonitor::niut_TIME_STR_<std::allocator<void> > niut_TIME_STR;

typedef boost::shared_ptr< ::humanMonitor::niut_TIME_STR> niut_TIME_STRPtr;
typedef boost::shared_ptr< ::humanMonitor::niut_TIME_STR const> niut_TIME_STRConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::humanMonitor::niut_TIME_STR_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace humanMonitor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::humanMonitor::niut_TIME_STR_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a84fc51d5840ce74cd63aaf10b060fb";
  }

  static const char* value(const  ::humanMonitor::niut_TIME_STR_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a84fc51d5840ce7ULL;
  static const uint64_t static_value2 = 0x4cd63aaf10b060fbULL;
};

template<class ContainerAllocator>
struct DataType< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "humanMonitor/niut_TIME_STR";
  }

  static const char* value(const  ::humanMonitor::niut_TIME_STR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# IDL struct ::niut::TIME_STR\n\
uint32 t_sec\n\
uint32 t_usec\n\
\n\
";
  }

  static const char* value(const  ::humanMonitor::niut_TIME_STR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.t_sec);
    stream.next(m.t_usec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct niut_TIME_STR_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanMonitor::niut_TIME_STR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::humanMonitor::niut_TIME_STR_<ContainerAllocator> & v) 
  {
    s << indent << "t_sec: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.t_sec);
    s << indent << "t_usec: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.t_usec);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUMANMONITOR_MESSAGE_NIUT_TIME_STR_H

